# Generated by Django 3.1.1 on 2020-09-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='posts',
            field=models.ManyToManyField(related_name='ta', to='tweets.Post'),
        ),
    ]
