# Generated by Django 3.1.1 on 2020-09-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tags_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='posts',
            field=models.ManyToManyField(related_name='tags_posta', to='tweets.Post'),
        ),
    ]
